apiVersion: v1
kind: Secret
metadata:
  name: database
type: Opaque
stringData:
  AUTH: "mongodb+srv://officialvinayakst_db_user:KCRHMj6nmMj8S4ZF@cluster0.ry4j36s.mongodb.net/auth"
  SANDBOX: "mongodb+srv://officialvinayakst_db_user:KCRHMj6nmMj8S4ZF@cluster0.ry4j36s.mongodb.net/sandbox"
  AI: "mongodb+srv://officialvinayakst_db_user:KCRHMj6nmMj8S4ZF@cluster0.ry4j36s.mongodb.net/ai"
  REDIS_URL: "redis://default:kNGJhRfaqc8Wp3C36a2IfzRKkKSthaUZ@redis-18172.c264.ap-south-1-1.ec2.cloud.redislabs.com:18172"
  RABBITMQ_URL: "amqps://snwnjpnz:NDkkMpx7Nwyoy8BpDQTpnTSxrgV4h5oU@capybara.lmq.cloudamqp.com/snwnjpnz"
