apiVersion: v1
kind: Secret
metadata:
  name: google
type: Opaque
stringData:
  GOOGLE_CLIENT_ID: "671701844485-squmbi7cfqsmpb5cb6asnqr2jlqsa9s5.apps.googleusercontent.com"
  GOOGLE_CLIENT_SECRET: "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"
  GOOGLE_REFRESH_TOKEN: "1//04nCFK4vKGbDKCgYIARAAGAQSNwF-L9Ir9vBjOLgnTqfj53eDHIZPr0bdMimkeidiYYNyTNJj_LAsTNsE79PE2N2Li7y-vDF-FpA"
  EMAIL_USER: "officialvinayakst@gmail.com"